# Generated by Django 4.2.1 on 2023-05-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sobremim'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
