# Generated by Django 4.2.1 on 2023-05-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_foto_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='nome',
            field=models.CharField(default='', max_length=60),
        ),
    ]
