# Generated by Django 4.2.1 on 2023-05-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_foto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='nome',
            field=models.CharField(default='', max_length=60),
        ),
    ]
