# Generated by Django 4.2.1 on 2023-05-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_foto_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamposAlteraveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo', models.CharField(max_length=60)),
                ('texto_campo', models.TextField()),
            ],
        ),
    ]
